#-------------------------------------|
# Settings are automatically updated, | 
# each time an action is performed.   |
#-------------------------------------|

# Keeps these folders in sync. The content of
# files with defined extensions will be parsed.
source: /DFormatter/source
target: /Denizen/scripts/generated

# After /fm reload, when successful, triggers this.
# Use /ex reload or another custom callback command.
command: reloadScripts

# For /fm reload, whether to execute the action 
# on another thread, to prevent lagg.
async: true

# Mirrors and parses files with these extensions.
# Files starting with a dot symbol are ignored.
extensions:
- .yml
- .dsc

# Parsed files will be saved with this extension.
extension: .dsc
